---
sudo: required
language: python

services:
  - docker

before_install:
  - git clone git://github.com/ome/omero-test-infra .omero

script:
  - .omero/docker app

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  distributions: sdist bdist_wheel
  on:
    tags: true
